//>>built
define(["dojo/_base/declare","dojo"],function(B,k){var r={},t={},n=function(a,b){var c="fld_"+a;b&&1==b&&(c+="[]");return c},x=function(a,b){0==b?w(a,void 0,["filteredNode","disabled"]):1==b||10==b?w(a,void 0,["filteredNode","hidden"]):2==b?u(a):3==b&&u(a)},y=function(){var a=k.byId("onlinesurvey_preview")&&"1"==k.byId("onlinesurvey_preview").value;if((a||"undefined"!=typeof g_aModule_course_ids&&g_aModule_course_ids.length)&&void 0!==g_aFilters&&0<g_aFilters.length)for(var b=g_aFilters.length-1;0<=
b;b--)1==g_aFilters[b].is_initial_filterset&&10==g_aFilters[b].action&&(a||g_aFilters[b].triggervalue[0]&&-1!=g_aModule_course_ids.indexOf(g_aFilters[b].triggervalue[0]))&&g_aFilters.splice(b,1)},u=function(a,b){C(a,b,["filteredNode","disabled","hidden"])},w=function(a,b,c){var f="slider_"+n(a,b),e=h(f);void 0!==e&&null!==e&&(require(["dojo/dom-attr"],function(a){a.set(f,"disabled",!0)}),k.addClass(e,"dijitSliderDisabled"),k.addClass(e,"dijitDisabled"));z(a,b,!0,!0,c)},C=function(a,b,c){z(a,b,!1,
!1,c);c=n(a);null!==h(c)&&h(c).style.removeProperty("display");var f="slider_"+n(a,b);a=h(f);void 0!==a&&null!==a&&(require(["dojo/dom-attr"],function(a){a.set(f,"disabled",!1)}),k.removeClass(a,"dijitSliderDisabled"),k.removeClass(a,"dijitDisabled"))},z=function(a,b,c,f,e){var g=n(a,b),d=v(g);if(0<d.length)for(g=0;g<d.length;g++)if(1==b)for(a=0;a<g_aFilters.length;a++)d[g].value==g_aFilters[a][2]&&(d[g].disabled=f,p(d[g],c,e));else"DIV"!=d[g].nodeName&&(d[g].disabled=f),p(d[g],c,e);else if(b=h("opt_"+
a),null!==b)b.disabled=f,p(b,c,e);else for(d=1;b=h(g+"_"+d);)b.disabled=f,p(b,c,e),d++},p=function(a,b,c){a=A(a,"item","static");for(var f=0;f<c.length;f++)if(1==b)a:{var e=a,g=c[f];if(e.className){for(var d=e.className.split(" "),h=d.length,l=0;l<h;l++)if(d[l]===g)break a;d.push(g);e.className=d.join(" ")}}else if(e=a,g=c[f],e.className){for(var d=e.className.split(" "),h=[],l=d.length,k=0;k<l;k++)d[k]!==g&&h.push(d[k]);e.className=h.join(" ")}},D=function(){var a=k.query(".item,.static");a.removeClass("filteredNode");
a.removeClass("hidden");a.removeClass("disabled");a=k.query("input,select,textarea").filter(function(a){return"btnback"!=a.id&&"btnnext"!=a.id});a.removeClass("filteredNode");a.attr("disabled",!1)},A=function(a,b,c){if(void 0===a)return!1;if(""!==a.className)for(var f=a.className.split(" "),e=0;e<f.length;e++)if(f[e]===b||void 0!==c&&f[e]===c)return a;a=a.parentNode;return void 0!==a?A(a,b,c):!1},v=function(a){if(!(a in r)){var b=k.query("[name\x3d'"+(a+"_1")+"']");0==b.length&&(b=k.query("[name\x3d'"+
a+"']"));0==b.length&&(b=k.query("[name\x3d'"+(a+"[]")+"']"));0==b.length&&(b=k.query("."+a));r[a]=b}return r[a]},h=function(a){a in t||(t[a]=document.getElementById(a));return t[a]},E=function(a){for(var b=0;b<g_aFilters.length;b++)for(var c=n(g_aFilters[b].triggerfldid),c=v(c),f=0;f<c.length;f++)(elem=c[f])&&elem.style&&("textarea"===elem.type||"text"===elem.type?(elem.onblur=a.doFiltering,elem.onkeyup=function(){g_openQuestionFilterTimer&&window.clearTimeout(g_openQuestionFilterTimer);g_openQuestionFilterTimer=
window.setTimeout(function(){a.doFiltering()},300)}):elem.addEventListener?elem.addEventListener("change",function(b){a.doFiltering()},!1):elem.attachEvent&&elem.attachEvent("onchange",function(b){a.doFiltering()}))};return B(null,{thisOnlineSurvey:null,constructor:function(){thisOnlineSurvey=this},doFiltering:function(a){if("object"==typeof k)D();else for(a=0;a<g_aFilters.length;a++)u(g_aFilters[a][2]);if(void 0!==g_aFilters)for("function"==typeof y&&y(),a=0;a<g_aFilters.length;a++)if(1==g_aFilters[a].is_initial_filterset)for(var b=
g_aFilters[a].targets,c=0;c<b.length;c++)x(b[c],g_aFilters[a].action);for(a=0;a<g_aFilters.length;a++)if(1!=g_aFilters[a].is_initial_filterset&&0<g_aFilters[a].triggerfldid){for(var b=g_aFilters[a].triggervalue,c=g_aFilters[a].targets,f=g_aFilters[a].action,e="fld_"+g_aFilters[a].triggerfldid,g=v(e),d=void 0,d=void 0,m=[],l=void 0,l=0;l<g.length;l++)d=g[l],1==d.checked&&0==d.disabled&&("radio"==d.type&&m.push(d.value),"checkbox"==d.type&&m.push(d.value));0==m.length&&(d=h(e))&&0==d.disabled&&"radio"!=
d.type&&m.push(d.value);0==m.length&&m.push(null);if(0<m.length)for(e=0;e<m.length;e++)if(null!=m[e]){l=!1;d=m[e].toString();if("undefined"!=typeof b.length)for(var g=0,n=b.length;g<n;g++)if(void 0!==b[g].string_value){if(0<=d.length){var p=parseInt(b[g].compare_method),q=b[g].string_value,d=d.toUpperCase(),q=q.toUpperCase();switch(p){case 1:d===q&&(l=!0);break;case 2:0===d.indexOf(q)&&(l=!0);break;case 3:-1!==d.indexOf(q)&&(l=!0)}}}else if(b[g]==d){l=!0;break}if(1==l)for(d=0;d<c.length;d++)x(c[d],
f)}}doneFiltering()},initFilteringRoutines:function(){for(var a=g_aFilters,b=[],c=[],f=0,e=a.length;f<e;f++)b=a[f].triggervalue,"string"!=typeof b&&(b=(new String(b)).split(",")),a[f].triggervalue.triggervalue=b,c.push(a[f]);g_aFilters=c;E(thisOnlineSurvey);thisOnlineSurvey.doFiltering();a=document.getElementsByTagName("button");for(b=0;b<a.length;b++)c=a[b].className,!1!==c.indexOf("printpreview")&&(c=c.replace(/hidden/g,"")),a[b].className=c},goPage:function(a){h("jumptopage").value=a;h("form_onlinesurvey").submit()},
changeLanguage:function(a){h("nLangIDchange").value=1;h("nLangID").value=a;g_oDynamicChapters.removeOnUnloadListener();a=h("form_onlinesurvey");var b=a.action;a.action=addIndicatorParam(a.action,"changeLang");a.submit();a.action=b},prepareprintpreview:function(){var a=h("form_onlinesurvey");showprintpreview(a.action)},showprintpreview:function(a){void 0==a&&(a=window.location.href);h("printpreview").value=0;var b=800,c=800;window.innerHeight&&(c=window.innerHeight-120);window.innerWidth&&(b=window.innerWidth-
120);window.open(a+"\x26printpreview\x3d2","printpreview","dependent\x3dyes,left\x3d10,top\x3d10,location\x3dno,menubar\x3dyes,resizable\x3dyes,scrollbars\x3dyes,toolbar\x3dno,width\x3d"+b.toString()+",height\x3d"+c.toString())},savetemp:function(){h("tempsave").value=1;g_oDynamicChapters.removeOnUnloadListener();var a=h("form_onlinesurvey"),b=a.action;a.action=addIndicatorParam(a.action,"tempSave");a.submit();a.action=b},validateMultipleChoiceMaxLength:function(a){var b=a.replace("fld_","").replace("[]",
""),c=document.querySelector('div[data-id\x3d"'+b+'"]').getAttribute("data-max-answers");a=document.querySelectorAll('input[name\x3d"'+a+'"]:checked').length;b+="_max_answers_reached";0<c&&(a>c?document.getElementById(b).style.display="block":document.getElementById(b).style.display="none")}})});
//# sourceMappingURL=onlinesurvey.js.map