#!/bin/bash

src=html
dest=output

cd $(git rev-parse --show-toplevel)

rm -r $dest

for file in $(find $src -type f); do
    output=${file/#$src/$dest}
    mkdir -p $(dirname $output)
    echo $file
    scripts/parse-file $file > $output
done

for dir in res scripts styles demos; do
    ln -s ../$dir $dest/$dir
done
