#!/bin/bash

# Configurable variables
export HTML_SRC=html
export HTML_ROOT=output
export TEMPLATE_DIR=templates

cd $(git rev-parse --show-toplevel)

rm -r $HTML_ROOT

for file in $(find $HTML_SRC -type f); do
    out_file=${file/#$HTML_SRC/$HTML_ROOT}
    mkdir -p $(dirname $out_file)
    echo $file
    scripts/parse-file $file > $out_file
done

for dir in res scripts styles; do
    ln -s $PWD/$dir $HTML_ROOT/$dir
done
