#!/bin/bash

set -e

cd $(git rev-parse --show-toplevel)
. .env

rm -r $dest/*

for file in $(find $src -type f); do
    out_file=${file/#$src/$dest}
    mkdir -p $(dirname $out_file)
    echo $file
    scripts/parse-file $file > $out_file
done

for dir in res styles; do
    cp -r $PWD/$dir $dest/$dir
done
